import { Prisma } from "@prisma/client";

export const businessProfileSummarySelect = {
  id: true,
  userId: true,
  name: true,
  handoffEnabled: true,
  identity: true,
  targetAudience: true,
  voice: true,
  tone: true,
  productsServices: true,
  expectedUserIntents: true,
  corePolicies: true,
  phoneNumbers: true,
  workingHours: true,
  address: true,
  customerDetailsInstructions: true,
  customerMemoryFields: true,
  aiBehaviorInstructions: true,
  followUpEnabled: true,
  followUpMode: true,
  followUpDelays: true,
  followUpInstructions: true,
  brandLogoUrl: true,
  brandPrimaryColor: true,
  brandSecondaryColor: true,
  brandAccentColor: true,
  visualAesthetic: true,
  artStyle: true,
  brandKitCompleted: true,
  brandKitUpdatedAt: true,
  brandWatermarkEnabled: true,
  watermarkPosition: true,
  facebookGreetingMode: true,
  facebookGreetingTemplate: true,
  scrapedWebsiteUrl: true,
  ragIngested: true,
  ragIngestedAt: true,
  plan: true,
  monthlyTokensUsed: true,
  monthlyCreditsUsed: true,
  monthlyCreditQuota: true,
  autoResetEnabled: true,
  createdAt: true,
  updatedAt: true,
  faqs: {
    select: {
      id: true,
      question: true,
      answer: true,
    },
  },
  knowledgeSections: {
    select: {
      id: true,
      title: true,
      content: true,
    },
  },
  facebookPages: {
    select: {
      id: true,
      pageId: true,
      pageName: true,
      category: true,
      pictureUrl: true,
      followersCount: true,
      isActive: true,
      businessProfileId: true,
    },
  },
  whatsAppAccounts: {
    select: {
      id: true,
      phoneNumberId: true,
      displayPhoneNumber: true,
      wabaId: true,
      isActive: true,
      businessProfileId: true,
    },
  },
} satisfies Prisma.BusinessProfileSelect;

export const businessProfileWithOwnerSelect = {
  ...businessProfileSummarySelect,
  user: {
    select: {
      id: true,
      name: true,
      email: true,
      role: true,
      plan: true,
      isActive: true,
    },
  },
} satisfies Prisma.BusinessProfileSelect;
