import type { AiTruthfulnessPolicy } from "@modules/ai-agent/core/aiEngine.utils";

type SupportedFallbackLocale = "en" | "ar-EG";

const ARABIC_VOICE_PATTERN = /arabic|عربي|egyptian/i;

// Emergency copy only. Normal recovery and handoff messages are generated by
// generateSafeRecoveryReply(), then validated before they reach the customer.
// These strings are used only if that AI recovery path fails or is unsafe twice.
const EMERGENCY_FALLBACK_CATALOG: Record<
  SupportedFallbackLocale,
  AiTruthfulnessPolicy["fallbackTemplates"]
> = {
  en: {
    unverified:
      "I can’t confirm this from the latest system data yet. Please send the exact details so I can verify them.",
    failed:
      "I can’t verify this right now. I’ll connect you with the team so they can confirm the details accurately.",
    smallTalkRecovery:
      "Hi! How can I help you today?",
  },
  "ar-EG": {
    unverified:
      "مش قادر أأكد المعلومة دي من بيانات النظام الحالية. ابعتلي التفاصيل المطلوبة بالظبط عشان أقدر أتحقق منها.",
    failed:
      "مش قادر أتحقق من المعلومة دي حالياً. هحوّلك لفريقنا عشان يأكدوا لك التفاصيل بدقة.",
    smallTalkRecovery:
      "أهلاً بيك! تحب تعرف إيه عن خدماتنا؟",
  },
};

export function resolveFallbackLocale(voice: string): SupportedFallbackLocale {
  return ARABIC_VOICE_PATTERN.test(voice) ? "ar-EG" : "en";
}

export function buildTruthfulnessPolicyForVoice(
  voice: string,
): Partial<AiTruthfulnessPolicy> {
  return {
    fallbackTemplates: EMERGENCY_FALLBACK_CATALOG[resolveFallbackLocale(voice)],
  };
}

export function buildNotIngestedReply(voice: string): string {
  if (resolveFallbackLocale(voice) === "ar-EG") {
    return "لسه بنجهز قاعدة معرفة البزنس. هحوّلك لفريقنا عشان يساعدك في الوقت الحالي.";
  }

  return "We're still setting up the business knowledge base. I'll connect you with the team so they can help for now.";
}
