/**
 * streamAgentGraph — Generator for real-time token streaming.
 *
 * This function wraps the agentGraph.streamEvents() call to yield
 * tokens as they are generated by the Gemini model inside the callGemini node.
 *
 * It filters for the 'ai_token' custom event dispatched in callGemini.ts.
 *
 * Usage:
 * for await (const token of streamAgentGraph(params)) {
 *   // Send token to client (SSE, WebSockets, etc.)
 * }
 */
import { agentGraph, type AgentGraphParams } from "./agentGraph";
import { logger } from "@utils/logger";
import prisma from "@config/prisma";
import { DEFAULT_AI_TRUTHFULNESS_POLICY } from "./aiEngine.utils";

export async function* streamAgentGraph(params: AgentGraphParams) {
  // ── Pre-flight data resolution (same as _runGraph) ────────────────────
  const profile = await prisma.businessProfile.findUnique({
    where:  { id: params.businessProfileId },
    select: { userId: true },
  });
  if (!profile) throw new Error("Business profile not found");

  const policy = {
    ...DEFAULT_AI_TRUTHFULNESS_POLICY,
    ...(params.policy ?? {}),
  };

  const historyContents = params.historyTurns.map((t) => ({
    role:  t.role,
    parts: t.parts ? t.parts : [{ text: t.text ?? "" }],
  }));

  const initialContents = [
    ...historyContents,
    { role: "user" as const, parts: [{ text: params.customerMessage || "" }] },
  ];

  const threadId = params.conversationId?.toString() || `stream_${Date.now()}`;

  const initialState = {
    systemInstruction: params.systemInstruction,
    tools:             params.tools,
    businessProfileId: params.businessProfileId,
    businessName:      params.businessName,
    businessVoice:     params.businessVoice,
    businessTone:      params.businessTone,
    userId:            profile.userId,
    customerPhone:     params.customerPhone,
    channel:           params.channel,
    contextQuality:    params.contextQuality,
    availableChunkTypes: params.availableChunkTypes ?? [],
    externalSourceFailureBehaviors: params.externalSourceFailureBehaviors ?? {},
    policy,
    responseMode:      params.responseMode ?? "AUTO",
    contents:          initialContents as any,
    functionCalls:     [] as any,
    turnCount:         0 as any,
    hadToolExecution:  false as any,
    sessionStats: {
      promptTokens:           0,
      completionTokens:       0,
      groundingCalls:         0,
      lastBilledPromptTokens: 0,
      lastBilledCompletionTokens: 0,
      lastBilledGrounding:    0,
      modelName:              "gemini-3-flash-preview",
    } as any,
    decision: null as any,
  };

  // ── Stream events from the graph ──────────────────────────────────────
  const eventStream = agentGraph.streamEvents(
    initialState,
    {
      version: "v2",
      configurable: {
        thread_id:     threadId,
        graph_version: "v1",
      },
    }
  );

  let fullResponseText = "";
  let lastYieldedLength = 0;

  for await (const event of eventStream) {
    if (event.event === "on_custom_event" && event.name === "ai_token") {
      const data = event.data as any;
      const token = data?.token;
      if (!token) continue;

      fullResponseText += token;

      // Robust streaming extractor for JSON field value
      const contentMatch = fullResponseText.match(/"content"\s*:\s*"([^]*)/);
      if (contentMatch) {
        let rawContent = contentMatch[1];
        
        // Find the actual end of the string (first unescaped quote)
        let trueEndIndex = -1;
        for (let i = 0; i < rawContent.length; i++) {
          if (rawContent[i] === '"') {
            // Count backslashes to ensure it's not escaped
            let backslashCount = 0;
            let j = i - 1;
            while (j >= 0 && rawContent[j] === '\\') {
              backslashCount++;
              j--;
            }
            if (backslashCount % 2 === 0) {
              trueEndIndex = i;
              break;
            }
          }
        }
        
        if (trueEndIndex !== -1) {
          rawContent = rawContent.substring(0, trueEndIndex);
        }

        try {
          // Let the native JSON parser handle all escaping (\n, \t, unicode)
          // This guarantees the streamed text will perfectly match the final saved text.
          const parsedContent = JSON.parse(`"${rawContent}"`);
          if (parsedContent.length > lastYieldedLength) {
            const newText = parsedContent.substring(lastYieldedLength);
            lastYieldedLength = parsedContent.length;
            yield { type: "token", data: newText };
          }
        } catch (e) {
          // The JSON string is incomplete (e.g. ends in the middle of \n or \u0645)
          // We safely ignore it and wait for the next token to complete the sequence.
        }
      }
    }
  }

  // ── Yield final result for database persistence ───────────────────────
  const finalState = await agentGraph.getState({
    configurable: { thread_id: threadId }
  });
  
  if (finalState.values.decision) {
    yield { type: "final_decision", data: finalState.values.decision };
  }
}



