/**
 * streamAgentGraph — Generator for real-time token streaming.
 *
 * This function wraps the agentGraph.streamEvents() call to yield
 * tokens as they are generated by the Gemini model inside the callGemini node.
 *
 * It filters for the 'ai_token' custom event dispatched in callGemini.ts.
 *
 * Usage:
 * for await (const token of streamAgentGraph(params)) {
 *   // Send token to client (SSE, WebSockets, etc.)
 * }
 */
import { agentGraph, type AgentGraphParams } from "./agentGraph";
import { logger } from "../../utils/logger";
import prisma from "../../config/prisma";
import { DEFAULT_AI_TRUTHFULNESS_POLICY } from "./aiEngine.utils";

export async function* streamAgentGraph(params: AgentGraphParams) {
  // ── Pre-flight data resolution (same as _runGraph) ────────────────────
  const profile = await prisma.businessProfile.findUnique({
    where:  { id: params.businessProfileId },
    select: { userId: true },
  });
  if (!profile) throw new Error("Business profile not found");

  const policy = {
    ...DEFAULT_AI_TRUTHFULNESS_POLICY,
    ...(params.policy ?? {}),
  };

  const historyContents = params.historyTurns.map((t) => ({
    role:  t.role,
    parts: t.parts ? t.parts : [{ text: t.text ?? "" }],
  }));

  const initialContents = [
    ...historyContents,
    { role: "user" as const, parts: [{ text: params.customerMessage || "" }] },
  ];

  const threadId = params.conversationId?.toString() || `stream_${Date.now()}`;

  const initialState = {
    systemInstruction: params.systemInstruction,
    tools:             params.tools,
    businessProfileId: params.businessProfileId,
    userId:            profile.userId,
    customerPhone:     params.customerPhone,
    channel:           params.channel,
    policy,
    responseMode:      params.responseMode ?? "AUTO",
    contents:          initialContents as any,
    functionCalls:     [] as any,
    turnCount:         0 as any,
    hadToolExecution:  false as any,
    sessionStats: {
      promptTokens:     0,
      completionTokens: 0,
      groundingCalls:   0,
      modelName:        "gemini-3-flash-preview",
    } as any,
  };

  // ── Stream events from the graph ──────────────────────────────────────
  const eventStream = agentGraph.streamEvents(
    initialState,
    {
      version: "v2",
      configurable: {
        thread_id:     threadId,
        graph_version: "v1",
      },
    }
  );

  let fullResponseText = "";
  let isExtracting = false;
  let hasFoundKey = false;
  
  // We look for "content": " inside the streaming JSON output.
  // This ensures the user only sees the actual message tokens.
  const targetKey = "content";

  for await (const event of eventStream) {
    if (event.event === "on_custom_event" && event.name === "ai_token") {
      const data = event.data as any;
      const token = data?.token;
      if (!token) continue;

      fullResponseText += token;

      // Simple streaming extractor for JSON field value
      // This is slightly brittle but effective for standard Gemini JSON output
      if (!isExtracting) {
        const keyMarker = `"${targetKey}": "`;
        const keyIndex = fullResponseText.indexOf(keyMarker);
        if (keyIndex !== -1 && !hasFoundKey) {
          hasFoundKey = true;
          isExtracting = true;
          // Yield the part of the token that might already be inside the value
          const remaining = fullResponseText.substring(keyIndex + keyMarker.length);
          if (remaining) yield { type: "token", data: remaining };
        }
      } else {
        // We are extracting. We need to watch for the closing quote.
        // This simple version doesn't handle escaped quotes perfectly but works for most chat.
        const closingQuoteIndex = token.indexOf('"');
        if (closingQuoteIndex !== -1) {
          isExtracting = false;
          const finalPart = token.substring(0, closingQuoteIndex);
          if (finalPart) yield { type: "token", data: finalPart };
        } else {
          yield { type: "token", data: token };
        }
      }
    }
  }

  // ── Yield final result for database persistence ───────────────────────
  const finalState = await agentGraph.getState({
    configurable: { thread_id: threadId }
  });
  
  if (finalState.values.decision) {
    yield { type: "final_decision", data: finalState.values.decision };
  }
}

